### ISSUE TITLE
.NET 5 Dependencies

### ISSUE THREAD

**Issue by epilsits** [TurnerSoftware/CacheTower#117]
There's no good way to handle this currently, but I'd caution bumping Microsoft dependencies to version 5.0.0 yet. I had this problem with some of our enterprise projects. We have an azure function app, and the functions sdk doesn't yet support any of the 5.0.0 dependencies, even if only targeting .net standard 2 / .net 3.1. There are open github issues you can find regarding this. If any of our function dependencies try to use the v5 packages, the app fails to initialize. The only solution is to stay at v3.1.10.

With the fixes you've released I'd like to give cachetower another go, but the v5 deps are a non-starter. I understand MS has created this problem, so do what is best for your library, they'll have to support v5 eventually.

**Comment by Turnerj** [comment]
Thanks for the heads up! Wasn't aware of this issue with the Azure Functions and 5.0 dependencies.
Is this an example of the issues you're talking about? https://github.com/Azure/azure-functions-vs-build-sdk/issues/472
(If so, I can then subscribe to it to track the issue and know when it is fixed so I can go back to updating the dependencies. If not, is there any that you're aware of that specifically reference this issue?)

Honestly, I'm not too fussed about delaying 5.0 dependencies till they are better supported, especially in situations like that. I'll do a 0.7.1 release with the two Microsoft 5.0 packages downgraded.

**Comment by epilsits** [comment]
Yep that's exactly it.

In our case our function app depends on core functionality in our larger project which has the caching layer. No way to decouple it without duplicating a large amount of code. We also have a couple internal nuget libraries which I had to downgrade after we were hit.

**Comment by Turnerj** [comment]
OK, no problem! I'll release an updated package with the downgraded dependencies in the next hour or so.

This information is good to know for my other libraries too - I have a few of them that Dependabot flagged for 5.0 dependencies.

**Comment by Turnerj** [comment]
0.7.1 released with the downgraded packages.
