### ISSUE TITLE
SetAsync and EvictAsync do not do remote eviction

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [TurnerSoftware/CacheTower#137]
I'm surprised I didn't notice this before, but SetAsync and EvictAsync don't do remote eviction through the redis remote eviction extension. This leaves incorrect cache data in other instance's memory cache for example.

This is a really critical feature for distributed cache.

**Comment by Turnerj** [comment]
Thanks for raising this! Yeah, that is a big oversight on my part - will work on a fix for this shortly.

**Comment by Turnerj** [comment]
Should be in the next few days! Keep the issues coming if you find any other problems or have any feature requests.

**Comment by Turnerj** [comment]
I've released v0.8.0 which contains this fix and the flush feature. Have a go with the update and let me know if you have any issues.

**Comment by ErikPilsits-RJW** [comment]
I've been using it from source for a week or so now, first with my fix for the remote eviction, then your updates. It's been working fine from what I can tell. I'll roll back into the nuget packages today. Thanks!
