### ISSUE TITLE
Bring your own serializer

### ISSUE THREAD

**Issue by vp89** [TurnerSoftware/CacheTower#158]
Wanted to see how you feel about giving a user the ability to bring their own serializer to the RedisCacheLayer or potentially any cache layer

The current situation as I understand it is:

MongoDB -> BSON only by virtue of the library used
Filesystem -> JSON or Protobuf, provided as 2 distinct implementations of ICacheLayer
Redis -> Protobuf only

It's a good choice to have Proto be the default, but it may increase adoption of the library if people are able to use JSON encoding without needing to implement their own ICacheLayer for Redis

It seems to me there are different ways this could be achieved, but wanted to first see if you are even open to the idea

**Comment by Turnerj** [comment]
Hey @vp89 - yeah, that's the current situation with serialization and yep, I'm open to the idea.

I originally went this particular method as it felt like a good option for simplicity though a good example of BYO serializer is JSON. Currently I use `Newtonsoft.Json` though for many cases, it could be just as beneficial to use `System.Text.Json`.

The biggest hurdle is: How do I change the setup without breaking the workflow too much for consumers? The library isn't v1.0.0 yet so according to SemVer, I can more-or-less break whatever I want but I still want to be careful about things.

Here are my rough thoughts:
- Create an `ICacheSerializer` interface in the `CacheTower` library with basic `SerializeObject<T>` and `DeserializeObject<T>` (may want async methods too for serializing to a stream).
- Create a new package called `CacheTower.Serializers.Protobuf` that has a Protobuf implementation of that interface.
- To be semi-backwards compatible (for one version at least) with `RedisCacheLayer`
  - Create a new constructor for the `RedisCacheLayer` to take an `ICacheSerializer`
  - The existing constructor will now create a `ProtobufCacheSerializer` for the new constructor (yay, backwards compatibility)

For the file-based ones, that is definitely going to be a breaking change but as a continuation of the list above:
- Create a new package called `CacheTower.Serializers.NewtonsoftJson`
- Create a new class called `FileCacheLayer` extending `FileCacheLayerBase` but takes an `ICacheSerializer`
- Deprecate `JsonFileCacheLayer`, `ProtobufFileCacheLayer` and `FileCacheLayerBase` classes
  - Once a version or two has passed, move the contents of `FileCacheLayerBase` into `FileCacheLayer` and remove the `CacheTower.Providers.FileSystem.Json` and `CacheTower.Providers.FileSystem.Protobuf` from NuGet.

In theory, that should cover everything that needs doing. Part of me wouldn't be against additionally doing these things:
- Moving `FileCacheLayer` to a new package `CacheTower.Providers.FileSystem`, leaving only `MemoryCacheLayer` in the core library
- Creating a `CacheTower.Serializers.SystemTextJson` package with that serializer (and then some serializer-based benchmarks)

The only con I see to this is that `JsonFileCacheLayer` does have a few minor optimizations for using `Newtonsoft.Json` and using a general serializer interface would remove that. That said, I think overall this is a good and important change so losing out on that isn't a huge deal.

If you want to approach adding this to the library, we'd probably do it in small stages but probably would follow the list above. What are you thoughts on that? Would love to hear your thoughts on this. 🙂

**Comment by vp89** [comment]
^ That's a good plan. I am trying to play around with all of these changes right now, I initially wanted to do it piecemeal like you described but was a little worried about coming up with an ICacheSerializer that doesn't fit well with all the different types of serializers that might need to be supported ... so I kind of skipped ahead some to try implementing all 3 of the above mentioned serializers based on the following interface:

https://github.com/TurnerSoftware/CacheTower/compare/master...vp89:byoserializer#diff-0cd55ee8cc9feb988deed2df8442453f058191458002b3bc185cbfdad1ebab93

I am having issues right now trying to implement a SystemTextJsonCacheSerializer because the Utf8JsonReader it's Deserialize method wants you to use doesn't take a Stream. LMK how that branch looks to you and if you have any ideas for solving this particular issue.

**Comment by Turnerj** [comment]
Had a quick look on my phone but I'm pretty sure `System.Text.Json` needs the call to be `DeserializeAsync`. Any time we are working with a real stream of data (like directly from a file), we'll likely want async deserializing. If we are working with strings, it won't matter.

**Comment by vp89** [comment]
Resuming discussion here, is the intent that there should be 1 internal type that represents a canonical CacheEntry<T> and then N types as needed that act as kind of DTOs for layer-specific representations of cache entries.

In that case, a design that could work is that the ICacheSerializer also has methods to serialize to/from these additional types:

`Stream SerializeRedisCacheEntry<T>(DateTime expiry, T? value);`
`IRedisCacheEntry<T> DeserializeRedisCacheEntry<T>(Stream stream);`
`Stream SerializeManifestEntry<T>(DateTime expiry, T? value);`
`IManifestEntry<T> DeserializeManifestEntry<T>(Stream stream);`

And each serializer package has 1 POCO for each of these that is properly tagged up with attributes.

This doesn't _feel_ very elegant, but maybe I am overthinking it.

**Comment by vp89** [comment]
^ Here is what that would look like ... https://github.com/TurnerSoftware/CacheTower/compare/master...vp89:movepocostoserializers

After this, the above refactors you suggested for the FileCacheLayer would be pretty easy to do.

**Comment by Turnerj** [comment]
I think externally from any serializer there should be just `CacheEntry<T>`. Each serializer then handles serializing a cache entry specifically - one of multiple ways it can serialize.

The interface would look something like:

```csharp
public interface ICacheSerializer
{
    Stream SerializeCacheEntry<T>(CacheEntry<T> cacheEntry);
    CacheEntry<T> DeserializeCacheEntry<T>(Stream value);
    Stream SerializeManifest(Dictionary<string, IManifestEntry> manifest);
    Dictionary<string, IManifestEntry> DeserializeManifest(Stream value);
    Stream SerializeValue<T>(T? value);
    T? DeserializeValue<T>(Stream value);
}
```

Whether the serializer uses its own POCO internally or not is an implementation detail for that particular serializer. For example, the JSON serializers could be implemented similar to here: https://github.com/TurnerSoftware/CacheTower/blob/1ac19fe2bd8b6e91ce9705400e05224785fb60b8/src/CacheTower.Providers.FileSystem.Json/JsonFileCacheLayer.cs#L26-L79

_Personally I'm not a huge fan of the "dictionary"-ness of the manifest being exposed but that is a separate issue._

What all these different methods allow is different ways values can be efficiently used by the cache layer. For example, Redis doesn't need to serialize the expiry date as that is separately encoded for Redis to auto-expire. For files, that needs to serialize a manifest and a raw value. Actually right now, I don't think any cache layer would be even using `SerializeCacheEntry<T>` like my example has - may only be worth adding once we have a cache layer that needs to store the expiry data directly alongside the main data.

**Comment by azhe403** [comment]
will this be possible can using Json serializer for RedisCacheLayer later?

**Comment by Turnerj** [comment]
> will this be possible can using Json serializer for RedisCacheLayer later?

That's the goal! I'll likely have first-party serializers for Newtonsoft.Json, System.Text.Json and protobuf-net. Right now I'm stuck with an issue with protobuf which is blocking my change - I might need to work out a different way for trying to architect it to work if I can't get my change merge and a new protobuf-net release out.
