### ISSUE TITLE
NuGet: No package Id exists

### ISSUE THREAD

**Issue by Turnerj** [TurnerSoftware/CacheTower#160]
Hey @miketimofeev - sorry to tag you this way but I can't comment on actions/virtual-environments#3038 (see screenshot below):

![image](https://user-images.githubusercontent.com/904226/114848013-717a1b00-9e1d-11eb-9a70-c902847eb6de.png)

Given that you wanted to know if the issue was still happening, I'm still experiencing it in _this_ repo, see the following action run: https://github.com/TurnerSoftware/CacheTower/runs/2351357022

Anyway, hopefully you get notified about this so you know the status of the fix. (Tried to see if there was another way to contact you but I couldn't find it easily)

**Comment by miketimofeev** [comment]
@Turnerj thanks for letting us know! We'll take a look at it. 
PS: we'll check the posting permission as well, sorry for the inconvenience

**Comment by miketimofeev** [comment]
@Turnerj I've forked your repo and check the behavior — there is no empty `$env:APPDATA\NuGet\nuget.config file` on the image, but it appears right after `choco install memurai-developer`. 
```
  gci $env:APPDATA\NuGet\
  choco install Memurai-Developer
  gci $env:APPDATA\NuGet\
```
Looks like it doesn't matter which choco package is installed, the file appears anyway 🤔

**Comment by Turnerj** [comment]
Great debugging to pick up that! Even with that being at least _a_ cause, I wonder why it seems to happen on and off. I guess if Chocolatey is the only cause, the inconsistent must exist on their side.

**Comment by miketimofeev** [comment]
Maybe it's somehow related to the .net version, I'm not an expert in this sphere, unfortunately

**Comment by Turnerj** [comment]
Closing this now that actions/virtual-environments#3038 is fixed and closed! 🎉
