### ISSUE TITLE
Question - Local Cache With Redis

### ISSUE THREAD

**Issue by MartyBJones** [TurnerSoftware/CacheTower#168]
I was wondering if the "RedisRemoteEvictionExtension" will notify the local in memory cache that an item has been invalidated?   The use case I am looking at is I get an item from the cache and it is stored in the local cache and then the item is updated in Redis,  Will the local in-memory cache be notified and remove the item from it's cache?

**Comment by Turnerj** [comment]
Hey @MartyBJones !

The general answer is "Yes" but there is a caveat - it will only do so if the item in Redis is updated by another `CacheStack` that has the `RedisRemoteEvictionExtension` configured. If you update Redis directly or by some other means, the local in-memory cache won't be aware of the change.

So say you have a `CacheStack` configured with an in-memory cache layer, the Redis cache layer and the `RedisRemoteEvictionExtension`. There are two (or more) web servers running with this configuration. Whether you call `cacheStack.SetAsync(myKey, myValue)` or `cacheStack.GetOrSetAsync(myKey, myFactoryMethod)`, a call that updates the cached data will be communicated via `RedisRemoteEvictionExtension` and will be removed from whatever cache layers are configured. When configuring the `RedisRemoteEvictionExtension`, you pass in what cache layers you want it to evict from.

Does that make sense?

**Comment by MartyBJones** [comment]
Makes perfect sense!

I am also looking for a c# redis client that supports the client side
caching but there doesn’t seem to be any that support the 6.0 feature yet.

**Comment by Turnerj** [comment]
Yeah, I'm hoping that SE.Redis gets support for the client side caching feature - then I could add support for that too.
