### ISSUE TITLE
Wrong dependency on CacheTower 1.0.0

### ISSUE THREAD

**Issue by jjonescz** [TurnerSoftware/CacheTower#176]
### What does the bug do?

Prevents installation of `CacheTower.Providers.Redis` (and maybe others).

### How can it be reproduced?

Install `CacheTower.Providers.Redis` version `0.10.0`. It has declared dependency on `CacheTower` version `1.0.0` which doesn't exist. So, it fails with error:

```txt
error NU1102: Unable to find package CacheTower with version (>= 1.0.0)
```

### Environment

- NuGet Package Version: 0.10.0
- .NET Runtime Version: .NET 5.0.302
- Operating System: Windows

**Comment by Turnerj** [comment]
Oh wow, that's bad. Will check it out tomorrow and get back to you.

**Comment by Turnerj** [comment]
Thanks for raising this - I believe I've isolated the problem to how (well, more specifically when in) the build process it goes wrong.

I use a custom build versioning library but it didn't trigger early enough in some conditions so it made part of the MSBuild targets fall to the default value of 1.0.0, specifically this part:

```xml
    <!--
      Determine project version for .NETCore projects
      Default to 1.0.0
      Use Version if it exists
      Override with PackageVersion if it exists (same as pack)
    -->
    <PropertyGroup Condition=" '$(PackageReferenceCompatibleProjectStyle)' == 'true' ">
      <_RestoreProjectVersion>1.0.0</_RestoreProjectVersion>
      <_RestoreProjectVersion Condition=" '$(Version)' != '' ">$(Version)</_RestoreProjectVersion>
      <_RestoreProjectVersion Condition=" '$(PackageVersion)' != '' ">$(PackageVersion)</_RestoreProjectVersion>
    </PropertyGroup>
```

I need to test out my particular fix but for now, have deprecated and hidden all of the v0.10.0 releases (except the main library) from NuGet.

**Comment by Turnerj** [comment]
I've fixed the issue in the repo and will release a new version in the next day or two - I have another bug I want to fix and get in the same release.

I'll leave this issue open till I've released the update.

**Comment by mgoodfellow** [comment]
Interestingly the 0.9.0 packages such as redis provider etc, seem to be tightly bound to the 0.9.0 core package of CacheTower.

I have tried to get 0.10.0 core working with the 0.9.0 provider/extensions providers, and everything looks right in the deps.json but I get a runtime failure when the provider package is loaded.

```
'[app].exe' (CoreCLR: clrhost): Loaded 'C:\[app]\bin\Debug\net5.0\CacheTower.Providers.Redis.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.IO.FileNotFoundException' in [app].dll
An exception of type 'System.IO.FileNotFoundException' occurred in [app].dll but was not handled in user code
Could not load file or assembly 'CacheTower, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

I will await your next release, as it is probably easier, but I have tried the various tricks to force bindings to a specific version (obvs binding redirects are a .NET Framework only thing), but I haven't managed to get it to load

**Comment by Turnerj** [comment]
Thanks for letting me know @mgoodfellow ! I had hoped it would work because it seems logically like it _should_ (the providers don't call the cache stack constructor etc) but yeah, it seems that the release is kinda borked being "half a release".

I'll deprecate the release on NuGet and push a new release very soon with everything fixed up.

**Comment by Turnerj** [comment]
Version 0.11.0 released that has the package reference issue fixed! Sorry for the hassle with that!
