### ISSUE TITLE
FileCachingLayer does not restore the saved data file even if the application is restarted. Manifest file empty.

### ISSUE THREAD

**Issue by muskara** [TurnerSoftware/CacheTower#187]
### What does the bug do?

Although it saves the json file of the data generated with FileCachingLayer (JsonFileCacheLayer) in the folder, it does not write its metadata to the manifest file. When the application is restarted, although the data file exists, it does not pull the cached data and calls it from the getter again.

### How can it be reproduced?

```csharp
// Startup.cs
services.AddCacheStack(
   new ICacheLayer[]
   {
       //new MemoryCacheLayer(),
       new JsonFileCacheLayer(@"D:\jsoncachelayer")
   },
    new[] {
        new AutoCleanupExtension(TimeSpan.FromMinutes(30))
    });

// Controller.cs
public async Task<IActionResult> IndexAsync()
{
    var model = await _cacheStack.GetOrSetAsync<IndexViewModel>($"indexviewmodel", async (old) =>
    {
        return await _lnwCache.GetHomepageIndexModel();
    }, new CacheSettings(TimeSpan.FromMinutes(15)));

    return View("Index", model);
}
```
```json
// manifest.json
{"Value":{}}
```
The file containing the data is stored in the folder named A1303B032BB63284F6F595600591AA13.json. But the manifest file is empty.

_P.S: Read and write permissions are defined to the folder._

- NuGet Package Version: 0.11.2
- .NET Runtime Version: .NET 5
- Operating System: Windows 10

**Comment by Turnerj** [comment]
Interesting - I designed the file cache layer to save the manifest file during dispose but I guess that it isn't being called by the service provider when the application shuts down.

There are a few options:
- Save the manifest every write (would affect performance - locks would happen on the manifest every write)
- Save the manifest via a background task on a schedule (every X minutes)

What I'm really curious about is why the dispose never occurs - I wonder if that relates to #167 - will need to investigate.

**Comment by Turnerj** [comment]
Looks like the problem is a combination of how the service collection handles disposing instances and how I add to the service collection. The short of it - if it isn't added a particular way, it causes the service provider to not dispose of the instances which prevents the saving of the file cache layer.

I've just tweeted about it here which shows the example a bit more: https://twitter.com/MrTurnerj/status/1431861485437796353

Anyway, hoping to find out about whether it is intended behaviour or not with the DI system. If it is, I'll update Cache Tower to use the method that works. If it isn't, I'll try and push for the change to be done to the DI system itself and just update the dependency.

Will keep you in the loop!

**Comment by Turnerj** [comment]
Yep, the DI system had this as intended behaviour so Cache Tower was just using it wrong. I've updated the service collection extensions to resolve this issue (allowing the cache stack and its layers to dispose, allowing the manifest to save).

I've just released v0.11.3 which includes the fix to the service collection/dependency injection so it should be disposed now (and thus trigger the manifest to save).

Let me know if it is still a problem after you've updated!

**Comment by muskara** [comment]
> Yep, the DI system had this as intended behaviour so Cache Tower was just using it wrong. I've updated the service collection extensions to resolve this issue (allowing the cache stack and its layers to dispose, allowing the manifest to save).
> 
> I've just released v0.11.3 which includes the fix to the service collection/dependency injection so it should be disposed now (and thus trigger the manifest to save).
> 
> Let me know if it is still a problem after you've updated!

Thank you very much for your effort, but nothing has changed and the problem still persists.

As far as I know Singleton Services can only be disposed when the application is closed. Considering I'm using this in a web application it will never dispose. Is there another point I missed?

**Comment by Turnerj** [comment]
> As far as I know Singleton Services can only be disposed when the application is closed. Considering I'm using this in a web application it will never dispose. Is there another point I missed?

So in your issue description, you mentioned that "When the application is restarted, although the data file exists, it does not pull the cached data and calls it from the getter again." - if the application is restarted, it should now correctly save the manifest file.

The manifest otherwise stays in memory while the application is running to avoid unnecessary file reads for cache expiry etc.

If, with the updated release, it still doesn't save the manifest during application restarts, it would mean an assumption of mine about it being disposed is wrong. Like an application crash would mean that the manifest isn't saved but a proper shutdown/restart "should" trigger the services to dispose properly.

**Comment by Turnerj** [comment]
I'm still contemplating potentially saving the manifest at regular intervals in the background but that is only a mild workaround to this - it should be saving the manifest when disposed and it should dispose on application shutdown/restart. The regular interval for saving though would help avoid issues with application crashes causing problems.

**Comment by muskara** [comment]
> I'm still contemplating potentially saving the manifest at regular intervals in the background but that is only a mild workaround to this - it should be saving the manifest when disposed and it should dispose on application shutdown/restart. The regular interval for saving though would help avoid issues with application crashes causing problems.

Now I understand better, it would be much more meaningful if you could at least include such fine details in the documentation.

When I close the application naturally, dispose is triggered and the manifest file is created successfully.
As I mentioned at the beginning, even if the name of the data file was included in the manifest, it could not find the file and load it. I did not notice the error that there is no exception catching in the data serialize and deserialize phases. I manually caught the error and this is what I got;


```
// JsonFileCacheLayer.cs (Deserialize)
Could not create an instance of type CacheTower.Providers.FileSystem.IManifestEntry. Type is an interface or abstract class and cannot be instantiated. Path 'Value.indexviewmodel.FileName', line 1, position 39.
```
```json
// manifest.json
{"Value":{"indexviewmodel":{"FileName":"A1303B032BB63284F6F595600591AA13.json","Expiry":"2021-08-29T12:13:23Z"}}}
```

**Comment by Turnerj** [comment]
> Now I understand better, it would be much more meaningful if you could at least include such fine details in the documentation.

Will look into adding a note about some of the specific semantics of file caching to the docs.

> When I close the application naturally, dispose is triggered and the manifest file is created successfully.

Good - that means the change did fix _that_ problem!

> As I mentioned at the beginning, even if the name of the data file was included in the manifest, it could not find the file and load it. I did not notice the error that there is no exception catching in the data serialize and deserialize phases. I manually caught the error and this is what I got;
> 
> ```
> // JsonFileCacheLayer.cs (Deserialize)
> Could not create an instance of type CacheTower.Providers.FileSystem.IManifestEntry. Type is an interface or abstract class and cannot be instantiated. Path 'Value.indexviewmodel.FileName', line 1, position 39.
> ```
> 
> ```json
> // manifest.json
> {"Value":{"indexviewmodel":{"FileName":"A1303B032BB63284F6F595600591AA13.json","Expiry":"2021-08-29T12:13:23Z"}}}
> ```

Looks like you identified a blind spot in my tests - while technically all of the code is called, it doesn't re-enter the file-based caches to trigger the behaviour of loading a manifest with existing entries. While the Protobuf file cache worked fine, the JSON file cache has the same error you noticed.

I've added tests for this behaviour and a fix (which was surprisingly simple) in #188 - I'll merge it shortly and release another patch version update.

**Comment by Turnerj** [comment]
So I should have this properly fixed now in v0.11.4 - let me know if you are still hitting issues!

**Comment by muskara** [comment]
Everything is fine and working properly. Thank you for your effort. 

There is one more thing I am wondering about. Is it possible to make a function that can manually refresh the data in the background? Same as with the staleAfter parameter but manually.
`cacheStack.RefreshValue(key, function?);`

**Comment by Turnerj** [comment]
> Everything is fine and working properly. Thank you for your effort.

Glad it is all working now!

> There is one more thing I am wondering about. Is it possible to make a function that can manually refresh the data in the background? Same as with the staleAfter parameter but manually.
> `cacheStack.RefreshValue(key, function?);`

That's an interesting idea - I've created #189 to track it. From what I'm picturing at the moment, it will likely need to take in the time-to-live value otherwise it can't save the refreshed value in the cache. The method will likely need to be async too as background refreshing kinda cheats by simply not awaiting internally on an action.
