### ISSUE TITLE
Caching layers support atomic operations?

### ISSUE THREAD

**Issue by celluj34** [TurnerSoftware/CacheTower#214]
Hello;

I am looking to implement your wonderful library into my application. I had a question, do the layers support atomic operations locally? As in, if Thread A and Thread B are trying to GetOrSet key "123" at the same time, will they both see a miss, and both try to run the factory?

**Comment by Turnerj** [comment]
Hey @celluj34 - thanks for raising the issue. Yeah, Cache Tower implements local refresh locking as well as [distributed refresh locking](https://github.com/TurnerSoftware/CacheTower#Distributed-Locking-via-Redis), preventing cache stampeding problems.
